### PR TITLE
Changes made in Theme

### PR DESCRIPTION
**Pull request by rhvsingh**

### CODE REVIEW

**Review by Nitesh-thapliyal — COMMENTED** [review]
can you please share snapshot of changes made, it will be helpfull

**Comment by rhvsingh** [comment]
Screenshot 2021-10-01 181426

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM
Thanks for Your Valuable Contribution : )

**Comment by adityamangal1** [comment]
@all-contributors please add @rhvsingh   for code contribution

**Pull request merged**
