### PR TITLE
feat: preload sounds

### LINKED ISSUE #8: sound lags on the first hit
The sound plays a little later on the first hit on the _deployed version_. I suspect its happening because the sound is getting fetched on the go.

Here is my solution and request it to be considered for **hactoberfest**.
I'll make the audios preload and will show a loader until its done.

### PR DESCRIPTION
**Pull request by g7i**
close: #8

### CODE REVIEW

**Comment by g7i** [comment]
Screenshot from 2021-10-02 10-52-48

**Review by harikanani — APPROVED** [review]
Cool 🙂

Looks good to me ✅

**Review by kamleshjoshi8102 — CHANGES_REQUESTED** [review]
Can you share link of Github page where you hosted this project : )

**Comment by g7i** [comment]
> Can you share link of Github page where you hosted this project : )

@kamleshjoshi8102 https://g7i.github.io/Drum-Kit/

**Comment by g7i** [comment]
Also, can the related issue be labelled as **hacktoberfest** ?

**Review by kevalvavaliya — CHANGES_REQUESTED** [review]
@g7i please resolve the issue so that we can merge your pr.
if facing any issue feel free to reach us.

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Comment by g7i** [comment]
> @g7i please resolve the issue so that we can merge your pr. if facing any issue feel free to reach us.
> 
> Organization linkpoint_right https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks Discord server link point_right https://join.bauddhikgeeks.tech/

@kevalvavaliya I have resolved the merge conflicts.

**Review by Nitesh-thapliyal — APPROVED** [review]

**Comment by adityamangal1** [comment]
@all-contributors please add @g7i   for code contribution

**Pull request merged**
