### PR TITLE
I have added a favicon in the website

### PR DESCRIPTION
**Pull request by shruti73**
I noticed that there was no favicon in the website so i have added favicon of a drum kit.

### CODE REVIEW

**Review by kevalvavaliya — APPROVED** [review]
Looks fine

**Review by kamleshjoshi8102 — CHANGES_REQUESTED** [review]
Can You Share a SnapShot of  your Changes : )

**Comment by shruti73** [comment]
image

**Review by harikanani — APPROVED** [review]
Looks Good to me

**Review by kevalvavaliya — APPROVED** [review]

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 
But try to improve or add more features in your code : )

**Comment by adityamangal1** [comment]
@all-contributors please add @shruti73 for code contribution

**Pull request merged**
