### PR TITLE
ui change

### PR DESCRIPTION
**Pull request by shaishav06**
I changed UI design . I'm begineer so i have changes as my site.

### CODE REVIEW

**Review by Nitesh-thapliyal — COMMENTED** [review]
Can you share the snapshot of changes made, it will be helpfull

**Comment by shaishav06** [comment]
image
image

**Comment by harikanani** [comment]
@shaishav06 Can you please resolve the conflicts

**Comment by shaishav06** [comment]
I can't understand What does mean by conflicts. can you tell me what does mean? and how to solve!

**Comment by harikanani** [comment]
You can find the resolve conflict button go through it

**Pull request closed without merging**
